### ISSUE TITLE
Solve outstanding issues

### ISSUE THREAD

**Issue by JJ** [perl6/Pod-To-Cached#1]
* [ ] finanalyst/pod-cached#24 Why pod names are lower-ased?
* [ ] finanalyst/pod-cached#23 Flapper: it fails some times
* [ ] finanalyst/pod-cached#22 Use specific exceptions classes
* [ ] finanalyst/pod-cached#21 Pod::To::Cached apparently hangs up when a new file is added
* [ ] finanalyst/pod-cached#20 Tests for several caches at the same time?
* [ ] finanalyst/pod-cached#18 If files are moved and the cache exists, it hangs up
* [ ] finanalyst/pod-cached#17 The constructor wrongly assumed the existence of a cache if the directory exists

**Comment by finanalyst** [comment]
re. #24, lower cased names.
I lower cased them in order to catch mis-spelt file names.
eg., if case-sensitive, then pod::To::Cached is different to Pod::To::Cached and a mis-spelt name would be allowed into the cache as well as the correct one. 

Case sensitivity did not seem as important for documentation files as it might be for variables. 

However, emitting a warning when a mis-spelling is detected is perhaps better.

**Comment by JJ** [comment]
But both paths might coexist in Linux; that means that it will cause a clash for valid path names.

**Comment by finanalyst** [comment]
The point is that we are dealing with Pod files. Is there any real possibility that documentation files are going to differ by the case of a letter in the name of the file for a valid reason?

Isn't it more likely that the difference of a different case of a letter in a file name is due to a misspelling? This occurred to me several times.

**Comment by finanalyst** [comment]
I seem to remember there was another reason I added the normalisation to lower case.

Some other package did not work properly when uppercase letters were used.

But I cannot remember exactly what it was.

**Comment by finanalyst** [comment]
JJ / Antonio, I want to work on the Specific exceptions class issue. 
Have you any preference for what it should be called?

**Comment by tbrowder** [comment]
How does the non-case nature of the Windows file system affect the issue? I've found over the years that Windows users (not devs so much) tend to be careless about such things compared to *nix users.

**Comment by JJ** [comment]
In general, we try to avoid such confusions, because the same happens to
Mac OSX users. But OSX keeps case, and Windows does it too, I think, even
if it's mapped to the same file if case is mixed.

Anyway, file name in the repository does not have anything to do with real
name, it's computed from the key (directory) and something else. We really
have to go through hoops to get the original name back in some cases, so I
don't really think this really serves some purpose.

Also, we do test now the whole stack in Windows, so we'll create specific
test cases for this so that we don't  find any trouble.

**Comment by finanalyst** [comment]
The windows exception might be why I normalised to lower case for the cache key names. I also stored the original name of the file in the index.json file so that the case-restored file name could be restored if need be from the key name.
Insisting on case-sensitive file names because *nix can seems to me to be overkill. ???

**Comment by JJ** [comment]
El lun., 30 sept. 2019 a las 17:52, Richard Hainsworth (<
notifications@github.com>) escribió:

> The windows exception might be why I normalised to lower case for the
> cache key names. I also stored the original name of the file in the
> index.json file so that the case-restored file name could be restored if
> need be from the key name.
> Insisting on case-sensitive file names because *nix can seems to me to be
> overkill. ???
>
It's not overkill, it's the default value and it's how they are actually
stored. It's simply storing the files using the same case that they are
stored originally.

**Comment by finanalyst** [comment]
I'm trying to duplicate the 'moving file' problem. 
After running tests 0-040* (not 050*), the test directory has a cache in 't/tmp/ref' and documents in 't/tmp/doc'.
Running `perl6 -Ilib -MPod::To::Cached` from the root directory of the repo and I enter REPL
I run `my Pod::To::Cached $c .= new(:path<t/tmp/rep>)`
Then in another terminal I move a Pod file from one sub directory of 't/tmp/doc' to another. 
in REPL, I run `$c.update-cache` and I get no error, nothing hangs or freezes.

I rerun `my Pod::To::Cached $c .= new(:path<t/tmp/rep>)` Again no ill effects.

I want to create a test file that generates the problem reported.

**Comment by JJ** [comment]
Just add a test for that. If it does not fail, then the problem might be
somewhere else, maybe in Documentable.
